openapi: 3.0.1
components:
  schemas:
    Distribution:
      type: object
      properties:
        kid:
          type: string
          description: The distribution KID
        donorId:
          type: integer
          description: The donor id
        taxUnitId:
          type: integer
          description: The tax unit id
        fundraiserTransactionId:
          type: integer
          description: Optional fundraiser transaction id, used to connect a donation to a fundraiser and a message to the fundraiser
        causeAreas:
          type: array
          items:
            $ref: "#/components/schemas/DistributionCauseArea"
      required:
        - kid
        - donorId
        - taxUnitId
        - causeAreas
      example:
        id: 1
        kid: "000013901401"
        donorId: 139
        taxUnitId: 1319
        causeAreas:
          - causeAreaId: 1
            name: "Global Health and Development"
            standardSplit: true
            percentageShare: "25.00"
            organizations:
              - id: 5
                name: "Against Malaria Foundation"
                percentageShare: "25.00"
              - id: 6
                name: "GiveWells tildelingsfond"
                percentageShare: "75.00"
          - causeAreaId: 2
            name: "Animal Welfare"
            standardSplit: true
            percentageShare: "75.00"
            organizations:
              - id: 5
                name: "Against Malaria Foundation"
                percentageShare: "25.00"
              - id: 6
                name: "GiveWells tildelingsfond"
                percentageShare: "75.00"
    DistributionCauseArea:
      type: object
      properties:
        id:
          type: number
          description: The cause area id
        name:
          type: string
          description: The cause area name
        standardSplit:
          type: boolean
          description: Whether the distribution is a standard distribution
        percentageShare:
          type: string
          description: The percentage share for the given cause area in decimal form
        organizations:
          type: array
          items:
            $ref: "#/components/schemas/DistributionCauseAreaOrganization"
      required:
        - id
        - standardSplit
        - percentageShare
        - organizations
      example:
        id: 1
        standardSplit: true
        percentageShare: "25.00"
        organizations:
          - id: 5
            name: "Against Malaria Foundation"
            percentageShare: "25.00"
          - id: 6
            name: "GiveWells tildelingsfond"
            percentageShare: "75.00"
    DistributionCauseAreaOrganization:
      type: object
      properties:
        id:
          type: integer
          description: The organization id
        name:
          type: string
          description: The organization name
        widgetDisplayName:
          type: string
          description: The organization widget display name
        percentageShare:
          type: string
          description: The percentage share for the given organizations in decimal form
      required:
        - id
        - percentageShare
      example:
        id: 5
        name: "Against Malaria Foundation"
        percentageShare: "25.00"
    DistributionInput:
      description: All of Distribution except KID
      type: object
      properties:
        donorId:
          type: integer
          description: The donor id
        taxUnitId:
          type: integer
          description: The tax unit id
        fundraiserId:
          type: integer
          description: Optional fundraiser id, if the distribution is a fundraiser distribution
        causeAreas:
          type: array
          items:
            $ref: "#/components/schemas/DistributionCauseArea"
      required:
        - donorId
        - taxUnitId
        - causeAreas
